---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: percona
  labels:
    name: percona
spec:
  replicas: 1
  selector: 
    matchLabels:
      name: percona 
  template: 
    metadata:
      labels: 
        name: percona
    spec:
      containers:
        - resources:
            limits:
              cpu: 0.5
          name: percona
          image: percona
          args:
            - "--ignore-db-dir"
            - "lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: k8sDem0
          ports:
            - containerPort: 3306
              name: percona
          volumeMounts:

            - mountPath: /etc/mysql/my.cnf
              subPath: my.cnf
              name: mysql-config 

            - mountPath: /sql-test.sh
              subPath: sql-test.sh
              name: sqltest-config

            - mountPath: /var/lib/mysql
              name: demo-vol1

          livenessProbe: 
            exec: 
              command: ["bash", "sql-test.sh"]
            initialDelaySeconds: 60
            periodSeconds: 1
            timeoutSeconds: 30
      volumes:

        - name: mysql-config 
          configMap: 
            name: mysqlconf 

        - name: sqltest-config
          configMap: 
            name: sqltest

        - name: demo-vol1
          persistentVolumeClaim:
            claimName: mysql-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
spec:
  storageClassName: openebs-standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  name: percona-mysql
  labels:
    name: percona-mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
      name: percona

