---
test_name: data_integrity_check

test_log_path: setup/logs/data_integrity.log

test_pod_regex: maya*|openebs*|pvc*|snapshot*|fio*

namespace: fio

snapshot: snapshot.yml

snapshot_claim: snapshot-claim.yml

fio_write: demo-fio-write-openebs.yml

fio_read: demo-fio-read-openebs.yml

fio_files:
  - demo-fio-write-openebs.yml
  - demo-fio-read-openebs.yml

snapshot_files:
  - snapshot.yml
  - snapshot-claim.yml

